apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-simple-app
  labels:
    app: super-simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: super-simple-app
  template:
    metadata:
      labels:
        app: super-simple-app
    spec:
      containers:
      - name: super-simple-app
        image: hr/super-simple-app:replaceImageTag
        ports:
        - containerPort: 8080